test_that("fun_get_ion_list()", {
  temp_full <- fun_get_ion_list()
  testthat::expect_true(is.data.table(temp_full))
  testthat::expect_true(temp_full[, .N] > 0)
  testthat::expect_true(all(c(-1, 1) %in% temp_full[, unique(charge)]))
  temp <- fun_get_ion_list(polarity = 0)
  testthat::expect_true(is.data.table(temp))
  testthat::expect_true(temp[, .N] > 0)
  testthat::expect_true(all(c(-1) %in% temp[, unique(charge)]))
  temp <- fun_get_ion_list(polarity = 1)
  testthat::expect_true(is.data.table(temp))
  testthat::expect_true(temp[, .N] > 0)
  testthat::expect_true(all(c(1) %in% temp[, unique(charge)]))
  temp_add <- fun_get_ion_list(losses = NULL)
  testthat::expect_true(all(c(-1, 1) %in% temp_add[, unique(charge)]))
  testthat::expect_true(temp_add[, .N] < temp_full[, .N])
  temp_loss <- fun_get_ion_list(adduct = NULL)
  testthat::expect_true(all(c(-1, 1) %in% temp_loss[, unique(charge)]))
  testthat::expect_true(temp_loss[, .N] < temp_full[, .N])
})
