test_that("fun_generate_ions_from_mz()", {
  for (mass_i in c(1, 1000)) {
    loss_db <- Spec2Annot::Losses_db[sample(seq_len(.N), 10), ]
    temp_full <- fun_generate_ions_from_mz(mass_i, losses = loss_db)
    testthat::expect_true(is.data.table(temp_full))
    testthat::expect_true(temp_full[, .N] > 0)
    testthat::expect_true(temp_full[is.na(relative_mass), .N] == 0)
    testthat::expect_true(all(c(-1, 1) %in% temp_full[, unique(charge)]))
    temp <- fun_generate_ions_from_mz(mass_i, polarity = 0, losses = loss_db)
    testthat::expect_true(is.data.table(temp))
    testthat::expect_true(temp[, .N] > 0)
    testthat::expect_true(all(c(-1) %in% temp[, unique(charge)]))
    testthat::expect_true(temp[is.na(relative_mass), .N] == 0)
    temp <- fun_generate_ions_from_mz(mass_i, polarity = 1, losses = loss_db)
    testthat::expect_true(is.data.table(temp))
    testthat::expect_true(temp[, .N] > 0)
    testthat::expect_true(all(c(1) %in% temp[, unique(charge)]))
    testthat::expect_true(temp[is.na(relative_mass), .N] == 0)
    temp_add <- fun_generate_ions_from_mz(mass_i, losses = NULL, polarity = 0)
    testthat::expect_true(all(c(-1) %in% temp_add[, unique(charge)]))
    testthat::expect_true(temp_add[, .N] < temp_full[, .N])
    testthat::expect_true(temp_add[is.na(relative_mass), .N] == 0)
    temp_loss <- fun_generate_ions_from_mz(mass_i, adduct = NULL, polarity = 0, losses = loss_db)
    testthat::expect_true(all(c(-1) %in% temp_loss[, unique(charge)]))
    testthat::expect_true(temp_loss[, .N] < temp_full[, .N])
    testthat::expect_true(temp_loss[is.na(relative_mass), .N] == 0)
    temp_iso <- fun_generate_ions_from_mz(mass_i, db_iso = NULL, polarity = 0, losses = loss_db)
    testthat::expect_true(all(c(-1) %in% temp_iso[, unique(charge)]))
    testthat::expect_true(temp_iso[, .N] < temp_full[, .N])
    testthat::expect_true(temp_iso[is.na(relative_mass), .N] == 0)
  }
})
