// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// brute_force_const
Rcpp::NumericMatrix brute_force_const(double mass, double ppm, Rcpp::NumericVector mass_vc, Nullable<Rcpp::NumericVector> maxiter_vc_, Rcpp::CharacterVector name_vc, int debugl, int debugit);
RcppExport SEXP _Spec2Annot_brute_force_const(SEXP massSEXP, SEXP ppmSEXP, SEXP mass_vcSEXP, SEXP maxiter_vc_SEXP, SEXP name_vcSEXP, SEXP debuglSEXP, SEXP debugitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type mass(massSEXP);
    Rcpp::traits::input_parameter< double >::type ppm(ppmSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mass_vc(mass_vcSEXP);
    Rcpp::traits::input_parameter< Nullable<Rcpp::NumericVector> >::type maxiter_vc_(maxiter_vc_SEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type name_vc(name_vcSEXP);
    Rcpp::traits::input_parameter< int >::type debugl(debuglSEXP);
    Rcpp::traits::input_parameter< int >::type debugit(debugitSEXP);
    rcpp_result_gen = Rcpp::wrap(brute_force_const(mass, ppm, mass_vc, maxiter_vc_, name_vc, debugl, debugit));
    return rcpp_result_gen;
END_RCPP
}
// find_comb
int find_comb(int n, int r);
RcppExport SEXP _Spec2Annot_find_comb(SEXP nSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(find_comb(n, r));
    return rcpp_result_gen;
END_RCPP
}
// annotate_spectra
Rcpp::NumericVector annotate_spectra(Rcpp::NumericVector mass);
RcppExport SEXP _Spec2Annot_annotate_spectra(SEXP massSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mass(massSEXP);
    rcpp_result_gen = Rcpp::wrap(annotate_spectra(mass));
    return rcpp_result_gen;
END_RCPP
}
// mz_vec_aggregate
Rcpp::NumericVector mz_vec_aggregate(Rcpp::NumericVector xx, double tt);
RcppExport SEXP _Spec2Annot_mz_vec_aggregate(SEXP xxSEXP, SEXP ttSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type xx(xxSEXP);
    Rcpp::traits::input_parameter< double >::type tt(ttSEXP);
    rcpp_result_gen = Rcpp::wrap(mz_vec_aggregate(xx, tt));
    return rcpp_result_gen;
END_RCPP
}
// mz_ppm
double mz_ppm(double massa, double massb);
RcppExport SEXP _Spec2Annot_mz_ppm(SEXP massaSEXP, SEXP massbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type massa(massaSEXP);
    Rcpp::traits::input_parameter< double >::type massb(massbSEXP);
    rcpp_result_gen = Rcpp::wrap(mz_ppm(massa, massb));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Spec2Annot_brute_force_const", (DL_FUNC) &_Spec2Annot_brute_force_const, 7},
    {"_Spec2Annot_find_comb", (DL_FUNC) &_Spec2Annot_find_comb, 2},
    {"_Spec2Annot_annotate_spectra", (DL_FUNC) &_Spec2Annot_annotate_spectra, 1},
    {"_Spec2Annot_mz_vec_aggregate", (DL_FUNC) &_Spec2Annot_mz_vec_aggregate, 2},
    {"_Spec2Annot_mz_ppm", (DL_FUNC) &_Spec2Annot_mz_ppm, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_Spec2Annot(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
