# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get mass deviation in ppm
#'
#' This function returns a numeric value
#' corresponding to the mass deviation
#' between `massa` and `massb` in ppm.
#'
#' @param massa First mass
#' @param massb Second mass
#' @export
#'
mz_ppm <- function(massa = 120.1253, massb = 120.1263) {
    .Call(`_Spec2Annot_mz_ppm`, massa, massb)
}

#' Group m/Z from a vector based on tolerance
#'
#' This function returns a matrix with m/Z groups
#' based on a tolerance.
#'
#' @param mass Targeted mass
#' @param ppm Mass tolerance in ppm to restrict results
#' @param maxiter_vc_ Vector of element maximum limits (optional) (size = n)
#' @param mass_vc Vector of elemnt masses (size = n)
#' @param name_vc Vector of elemnt names (size = n)
#' @param debugl Integer (0: no message, 1: short, 2: verbose)
#' @param debugit Integer for max iter to do
#' @export
#'
brute_force_const <- function(mass = 120, ppm = 5, mass_vc = 0L, maxiter_vc_ = NULL, name_vc = 0L, debugl = 0L, debugit = 0L) {
    .Call(`_Spec2Annot_brute_force_const`, mass, ppm, mass_vc, maxiter_vc_, name_vc, debugl, debugit)
}

#' Group m/Z from a vector based on tolerance
#'
#' This function returns a matrix with m/Z groups
#' based on a tolerance.
#'
#' @param xx A numeric and sorted vector of m/Z
#' @param tt Tolerance in absolute m/Z to group peaks
#' @export
#'
mz_vec_aggregate <- function(xx, tt) {
    .Call(`_Spec2Annot_mz_vec_aggregate`, xx, tt)
}

