# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Group m/Z from a vector based on tolerance
#'
#' This function returns a matrix with m/Z groups
#' based on a tolerance.
#'
#' @param mass Targeted mass
#' @param ppm Mass tolerance in ppm to restrict results
#' @param maxiter_vc_ Vector of element maximum limits (optional) (size = n)
#' @param mass_vc Vector of elemnt masses (size = n)
#' @param name_vc Vector of elemnt names (size = n)
#' @param debugl Integer (0: no message, 1: short, 2: verbose)
#' @param debugit Integer for max iter to do
#' @export
#'
brute_force_const <- function(mass = 120, ppm = 5, mass_vc = 0L, maxiter_vc_ = NULL, name_vc = 0L, debugl = 0L, debugit = 0L) {
    .Call(`_Spec2Annot_brute_force_const`, mass, ppm, mass_vc, maxiter_vc_, name_vc, debugl, debugit)
}

#' Find all combination
#'
#' This function returns edges of networked
#' ions
#'
#' @param n number of pairs to create
#' @param r number of element in each pairs
#' @export
#'
find_comb <- function(n, r) {
    .Call(`_Spec2Annot_find_comb`, n, r)
}

#' Annotate a matrix and return network edges
#'
#' This function returns edges of networked
#' ions
#'
#' @param mass A numeric vector
#' @export
#'
annotate_spectra <- function(mass) {
    .Call(`_Spec2Annot_annotate_spectra`, mass)
}

combn_cpp <- function(m, r) {
    .Call(`_Spec2Annot_combn_cpp`, m, r)
}

#' Group m/Z from a vector based on tolerance
#'
#' This function returns a matrix with m/Z groups
#' based on a tolerance.
#'
#' @param xx A numeric and sorted vector of m/Z
#' @param tt Tolerance in absolute m/Z to group peaks
#' @export
#'
mz_vec_aggregate <- function(xx, tt) {
    .Call(`_Spec2Annot_mz_vec_aggregate`, xx, tt)
}

#' Get index in range
#'
#' @param input a numeric vector
#' @param valA a numeric value for the lower bound
#' @param valB a numeric value for the higher bound
#' @export
#'
get_range <- function(input, valA, valB) {
    .Call(`_Spec2Annot_get_range`, input, valA, valB)
}

#' Match two table
#'
#' This function match two table, searching every
#' entries in B which are contained in A mz +- ppmtol
#' and A.rt +- rttol
#'
#' @param db_dt a data.frame with at least mz and rt values (ref table)
#' @param exp_dt a data.frame with at least mz and rt values (exp table)
#' @param ppmtol a numeric value for the ppm tolerance
#' @param rttol a numeric value for the rt tolerance
#' @param debugL logical to print debug message
#' @export
#'
match_tables <- function(db_dt, exp_dt, ppmtol, rttol, debugL = FALSE) {
    .Call(`_Spec2Annot_match_tables`, db_dt, exp_dt, ppmtol, rttol, debugL)
}

#' Get mass deviation in ppm
#'
#' This function returns a numeric value
#' corresponding to the mass deviation
#' between `massa` and `massb` in ppm.
#'
#' @param massa First mass
#' @param massb Second mass
#' @export
#'
mz_ppm <- function(massa = 120.1253, massb = 120.1263) {
    .Call(`_Spec2Annot_mz_ppm`, massa, massb)
}

#' Get mass range with ppm
#'
#' @param mass First mass
#' @param ppm ppm tolerance
#' @export
#'
mz_range <- function(mass = 120.1253, ppm = 10) {
    .Call(`_Spec2Annot_mz_range`, mass, ppm)
}

